name: wiki
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  website:
    name: website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install rust
        run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      - name: install
        run: |
          cargo install mdbook
          cargo install book-summary
      - name: render manual
        run: |
          cargo run --target=x86_64-unknown-linux-gnu -- man -o ./markdown -f markdown
          cat ./markdown/complate.md >> ./docs/wiki/src/reference.md
          cat ./docs/README.md >> ./docs/wiki/src/index.md
          cd ./docs/wiki
          book-summary -yms
          mdbook build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/wiki/book
